[target.x86_64-unknown-linux-gnu]
rustflags = [
    '--cfg=tokio_unstable',
    "-Ctarget-cpu=x86-64-v3",
    "-Clink-arg=-fuse-ld=mold",
]

[target.aarch64-unknown-linux-gnu]
rustflags = ['--cfg=tokio_unstable', "-Clink-arg=-fuse-ld=mold"]
