name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Fmt and clippy
    strategy:
      matrix:
        rust-version: ['nightly']
        cache-key: ['']
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      
      - name: "Install Rust"
        run: |
          rustup toolchain install ${{ matrix.rust-version }} --profile minimal --no-self-update
          rustup default ${{ matrix.rust-version }}
          rustup component add rustfmt clippy --toolchain ${{ matrix.rust-version }}
        shell: bash

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run clippy
        if: success() || failure()
        run: cargo clippy --all -- -D clippy::all -D warnings
        # uses: actions-rs/clippy-check@v1
        # with:
        #   token: ${{ secrets.GITHUB_TOKEN }}
        #   args: -- -D clippy::all -D warnings
      - name: Run cargo fmt
        run: cargo fmt --all -- --check